/usr/local/qemu/bin/qemu-system-riscv64 \
    -kernel \
    ./aster-nix-osdk-bin.qemu_elf \
    -initrd \
    ./initramfs.cpio.gz \
    -append \
    "SHELL=/bin/sh LOGNAME=root HOME=/ USER=root PATH=/bin:/benchmark init=/usr/bin/busybox ostd.log_level=trace -- sh /test/boot_hello.sh" \
    -cpu \
    rv64,zba=true,zbb=true,svpbmt=true \
    -machine \
    virt \
    -m \
    8G \
    --no-reboot \
    -nographic \
    -display \
    none \
    -serial \
    chardev:mux \
    -monitor \
    chardev:mux \
    -chardev \
    stdio,id=mux,mux=on,signal=off,logfile=qemu.log \
    -drive \
    if=none,format=raw,id=x0,file=./ext2.img \
    -drive \
    if=none,format=raw,id=x1,file=./exfat.img \
    -device \
    virtio-blk-device,drive=x0 \
    -device \
    virtio-blk-device,drive=x1 \
    -device \
    virtio-net-device,netdev=net0 \
    -netdev \
    user,id=net0,hostfwd=tcp::10000-:22 \
    -device \
    virtio-keyboard-device \
    -device \
    virtio-serial-device \
    -device \
    virtconsole,chardev=mux \
